services:
  postgres:
    image: postgres:18
    ports:
      - '5431:5432'
    environment:
      POSTGRES_USER: nestjs-dash
      POSTGRES_PASSWORD: nestjs-dash
      POSTGRES_DB: nestjs_dash_example_audit_log
    volumes:
      - audit_log_postgres_data:/var/lib/postgresql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U nestjs-dash -d nestjs_dash_example_audit_log']
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  audit_log_postgres_data:
